version: 2
jobs:
  build-job:
    docker:
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies 
          command: apt-get update; apt-get install -y openssh-client ca-certificates openssl;
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Login to Docker Hub 
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Build Image 
          command: |
            docker build -t eslater/wp-site:$CIRCLE_BUILD_NUM -t eslater/wp-site:latest docker/
      - run: 
          name: Push to Docker Hub 
          command: |
            docker push eslater/wp-site:$CIRCLE_BUILD_NUM
            docker push eslater/wp-site:latest
  deploy-job:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install Dependencies 
          command: apt-get update; apt-get install -y openssh-client ca-certificates openssl;
      - run:
          name: Deploy Latest
          command: ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "./pull-latest-and-redeploy.sh"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
