version: 2
dependencies:
  pre:
    - apt-get update; apt-get install -y open-ssh-client ca-certificates openssl zip;
jobs:
  build-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
          name: Zip Site Files
          command: |
            cd ..
            zip -r site-bundle.zip build 
            mkdir build/workspace
            mv site-bundle.zip build/workspace 
      - persist_to_workspace:
          root: /tmp/build/
          paths: workspace
          

  deploy-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - attach_workspace:
          at: /tmp/build/workspace
      - run:
          name: Move Site Bundle to Droplet 
          command: scp -o StrictHostKeyChecking=no workspace/site-bundle.zip $DROPLET_USER@$DROPLET_IP:~
      - run:
          name: Move Site Bundle to Droplet 
          command: ssh -v $DROPLET_USER@$DROPLET_IP "unzip site-bundle.zip; cd site-bundle; ./create_site.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
