version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Test 
          command: |
            set -x 
            ls
            pwd
            cd ..
            pwd
            touch test
            ls 
