version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
         name: Install PHP libzip-dev
         command: sudo apt-get install -y libzip-dev
      - run:
          name: Test 
          command: |
            cd ..
            zip -r project.zip project
            ls 
deployment:
  staging:
    branch: master
    command: |
       ls
       cd ..
       ls
