version: 2
jobs:
  build-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
         name: Install Zip 
         command: |
            apt-get update -y 
            apt-get install -y zip 
      - run:
          name: Test 
          command: |
            cd ..
            ls 
  deploy-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - run:
        name: Stage Deploy 
        command: |
           ls
           cd ..
           ls
