version: 2
jobs:
  build-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - checkout
      - run:
         name: Install Zip 
         command: |
            apt-get update -y 
            apt-get install -y zip 
      - run:
          name: Zip Site Files
          command: | 
            cd ..
            zip -r "site-bundle.zip" build 
  
  deploy-job:
    docker:
      - image: debian:stretch
    working_directory: /tmp/build
    steps:
      - run:
          name: Install scp 
          command: apt-get update -y && apt-get install scp 
      - run:
          name: Move Site Bundle to Droplet 
          command: scp site-bundle.zip $DROPLET_USER@$DROPLET_IP:~
      - run:
          name: Move Site Bundle to Droplet 
          command: ssh -v $DROPLET_USER@$DROPLET_IP "unzip site-bundle.zip; cd site-bundle; ./create_site.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
