version: '3.1'

services:
  wp-site:
    image: eslater/wp-site:latest 
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    #  - '443:443' 
    
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_PASSWORD: password 
      WORDPRESS_DB_USER: demo_user
      WORDPRESS_DB_NAME: demo_db
      WORDPRESS_DB_HOST: mariadb
    restart: always
    networks:
      - wordpress-network
    links:
      - mariadb:wp-site
    volumes:
      - demo_site:/var/www/html
    #deploy:
      #restart_policy:
        #condition: any
        #delay: 5s
        #max_attempts: 300
        #window: 120s  
  mariadb:
    image: mariadb  # this will use mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=demo_user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - demodb:/var/lib/mysql
    networks:
      - wordpress-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    links:
      - "mariadb:db"
    networks:
      - wordpress-network
volumes:
  demodb:
  demo_site:
networks:
  wordpress-network:
    driver: bridge
